/* ============================================================================
** Copyright (C) 2020 Infineon. All rights reserved.
**               Infineon Technologies, PSS SYS / DES
** ============================================================================
**
** ============================================================================
** This document contains proprietary information. Passing on and
** copying of this document, and communication of its contents is not
** permitted without prior written authorisation.
** ============================================================================
**
** Created on:  2020-08-19
*
 *      Author: kotvytsr
 */



#include "dtimer_drv.h"
#include "telemetry_drv.h"
#include "regulation_api.h"
#include "faults_api.h"
#include "faults_drv.h"
#include "pmbus_api.h"
#include "pmbus_gpio_control.h"
#include "shasta_hal_vsen.h"
#include "shasta_hal_vcontrol.h"
#include "shasta_hal_pwm.h"
#include "shasta_hal_pid.h"
//#include "shasta_hal_regulation.h"
#include "shasta_hal_scu.h"
#include "shasta_hal_cgu.h"
#include "shasta_hal_rgu.h"
#include "shasta_hal_telem.h"
#include "shasta_hal_common.h"
#include "shasta_hal_fault.h"
#include "shasta_hal_isen.h"
#include "regulation_state_machine_callbacks.h"
#include "pmbus_autogen.h"
#include "pmbus_mfr_autogen.h"
#include "user_app.h"
#include "cmsis_os.h"                   // ARM::CMSIS:RTOS:Keil RTX
#include "cmsis_os_ext.h"                   // ARM::CMSIS:RTOS:Keil RTX ext
#include "log_app.h"             /* Logging of errors */
#include "user_ntc_temperature_lut.h"
#include "patch_rom_table.h"
#include "string.h"
#include "add_on_features.h"
//#include "ramp_data.h"
//#include "uart_drv.h"                // uart driver functions
#include "pmbus_mfr_specific_handlers.h"

#include "buck_boost.h"
/**
 * Main entry point of the user application.  Good place to set breakpoint when debugging a patch.
 */

void patch_pmbus_mfr_autogen_init(void);


void patch_pmbus_mfr_autogen_init(void)
{
	pmbus_mfr_autogen_init();
}

void user_drv_init(void)
{
	memset(&user_data, 0, sizeof(USER_DATA_t));  // ZI the user data
	ntc_temp = &user_ntc_temp_lut[0];  // set the ntc lut to rom constant table


#ifdef iout_correction_feature_en
	patch_rom_table.patch_Telemetry_get = patch_Telemetry_get;
#endif


#if defined (feed_forward_feature_en) || defined(zvs_feature_en) || defined(light_load_features_en)
	patch_rom_table.patch_Regulation_Compute_Feed_Forward = patch_Regulation_Compute_Feed_Forward;
#endif


#ifdef eff_table_feature_en
	patch_rom_table.patch_Telemetry_Sample = patch_Telemetry_Sample;
#endif

	// this is the initialization of user pmbus commands autogenerated from pmbus spreadsheet
	ptr_mfr_specific_init = (mfr_specific_init_ptr) patch_pmbus_mfr_autogen_init;
	set_module_init_cb(MODULE_REGULATION, regulation_sm_callbacks_init);  // set the pointer funtion in init of regulation state machine to user callback setup for each state

	add_on_features_init();
	regulation_sm_callbacks_init();
	patch_pmbus_mfr_autogen_init();

}



