/* ============================================================================
** Copyright (C) 2019 Infineon Technologies AG
** All rights reserved.
** ============================================================================
**
** ============================================================================
** This document contains proprietary information of Infineon Technologies AG.
** Passing on and copying of this document, and communication of its contents
** is not permitted without Infineon's prior written authorisation.
** ============================================================================
*/
/**
 * @file    version.h
 * @brief   Contains the version information of the firmware image.
 */

#ifndef VERSION_H
#define VERSION_H

/* Always include the fw-wide configuration file first, its macros may rule the
 * implementation in subsequent include and someone might forget to include it.
 */
#include "fw_config.h"

/* Standard library */
#include <stdint.h>     // uint*_t

/* ============================================================================
 * Public data types
 * ========================================================================= */

/*lint -esym(714, version_number) -esym(759, version_number) -esym(765, version_number)
* This variable is automatically generated by a script, it marks the version number.  */
/** This variable describes the current firmware version number. */
extern const uint32_t version_number;

/** This variable describes the current firmware version timestamp. This 
    number might be modified by applied patches. */
extern uint32_t version_timestamp;

#endif /* VERSION_H */
